Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  # root user
  RootUsername: admin
  RootPassword: 123456
  # 日志
  LogSavePath: storage/logs
  LogFileName: server
  LogFileExt: .log
  # 分页
  DefaultPageSize: 10
  MaxPageSize: 100
  # 文件上传
  UploadSavePath: storage/upload
  UploadServerUrl: /static
  UploadImageMaxSize: 5   # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
  UploadDocMaxSize: 10  # MB
  UploadDocAllowExts:
    - .csv
    - .doc
    - .docx
  # 初始化
  InitTablesSqlPath: scripts/init_tables.sql
Database:
  DBType: mysql
  Username: root
  Password: root
  Host: 127.0.0.1
  Port: 3306
  DBName: cose
  Charset: utf8
  ParseTime: True
  MultiStatements: True
  MaxIdleConns: 10
  MaxOpenConns: 30
JWT:
  Secret: thisissecret
  Issuer: commmon-service
  RefreshExpire: 720   # hours
  AccessExpire: 168   # hours
Casbin:
  ModelFilePath: configs/rbac_model.conf
Redis:
  Addr: 127.0.0.1:6379
  DB: 0